cat <<'EOF' > netlify.toml
[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/next"
EOF

git add netlify.toml
git commit -m "chore: Netlify config (npm build)"
git push
